version: "2"
 
services:
  portainer:
    restart: unless-stopped
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    networks:
      - web
    ports: 
      - "9000:9000"
    labels:
      - traefik.docker.network=web
      - traefik.frontend.rule=Host:traefik.harro.dev
      - traefik.port=9000
      - traefik.backend=portainer
 
networks:
  web:
    external: true

volumes: 
  data: