  labels:
  - "traefik.enable=true"
  - "traefik.port=80"
  - "traefik.http.routers.cloud.entrypoints=websecure"
  # fill in hostname (eg. traefik.harro.dev)
  - "traefik.http.routers.cloud.rule=Host(`yourhostname`)"
  - "traefik.http.routers.cloud.tls.certresolver=mytlschallenge"
  - "traefik.http.routers.cloud.middlewares=cloud@docker"
  - "traefik.docker.network=webproxy"
  - "traefik.http.middlewares.cloud.headers.customFrameOptionsValue=SAMEORIGIN"
  - "traefik.http.middlewares.cloud.headers.framedeny=true"
  - "traefik.http.middlewares.cloud.headers.sslredirect=true"
  - "traefik.http.middlewares.cloud.headers.stsIncludeSubdomains=true"
  - "traefik.http.middlewares.cloud.headers.stsPreload=true"
  - "traefik.http.middlewares.cloud.headers.stsSeconds=15552000"